### ISSUE TITLE
lambda:local fails

### ISSUE THREAD

**Issue by quedicesebas** [IamDeshRaj/myPleaks#1]
I'm getting `{"currentRoute":"get - /","error":"Serverless-offline: route not found.","existingRoutes":["get - /production","get - /production/{proxy*}"],"statusCode":404}`

I changed/added this files in my project:

![image](https://user-images.githubusercontent.com/1771574/82532331-bf4fab80-9b06-11ea-8a34-7f85d2ed3215.png)

Anything missing? Thanks!

**Comment by IamDeshRaj** [comment]
simply use /production with your host e.g.  local:8080/production

**Comment by quedicesebas** [comment]
Jus saw your comment, trying...

**Comment by quedicesebas** [comment]
Nop, adding /production (http://localhost:3000/production) results in 502 error (Bad Gateway)

**Trace**:

offline: GET /production (λ: api)
offline: Failure: Cannot find module 'C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\lambda'
Require stack:
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\InProcessRunner.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\handler-runner\in-process-runner\index.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\handler-runner\HandlerRunner.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\handler-runner\index.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\LambdaFunction.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\LambdaFunctionPool.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\Lambda.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\lambda\index.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\ServerlessOffline.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\index.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless-offline\dist\main.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless\lib\classes\PluginManager.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless\lib\Serverless.js
- C:\Users\srrge\dev\tourbitz\gitlab\tours.tourbitz.com\node_modules\serverless\lib\utils\autocomplete.js

**Comment by IamDeshRaj** [comment]
Hi @sebrojas14 
I have built this [YouTube Video](https://youtu.be/RKhyDUaWB9Q), You can follow it along.
You need the latest angular CLI which is currently 9.1.5 perhaps.
If you want to deploy app on AWS you will need to configure AWS profile.

**Comment by quedicesebas** [comment]
Ypur code is working, I just don't achieve tu move changes to my project.

**Comment by IamDeshRaj** [comment]
Do the following things:-
1. Move your app folder components to app folder of my Repo.
2. Merge the following classes carefully in the app folder 
      1. AppModule with my Repo AppModule.
      2. AppComponent with my Repo AppComponent(including html, css).
      3. AppRoutingModule with my Repo AppRoutingModule.
3. Move assets to the assets folder.
4. Merge index.html and style.css carefully.
5. Have a look in angular.json if you need to add some path there for CSS and Style.
6. Remove index.html from ngsw-config.json to reflect the latest changes.
![image](https://user-images.githubusercontent.com/6917620/82723307-ae13c400-9ceb-11ea-83c5-39f6373749b1.png)

**Comment by sebrojas14** [comment]
Gonna try

**Comment by quedicesebas** [comment]
Do you know about this? (It is from your project, just downloaded, unziped and `npm install` and `npm run local:serverless`. Various angular files because its asking for without `/production` url part.
![image](https://user-images.githubusercontent.com/1771574/82797289-78cabb80-9e3c-11ea-9d32-b6791ef95a17.png)

For example, http://localhost:3000/styles.09e2c710755c8867a460.css is not resolving, and thats the first file the document is trying to retrieve. The same with other.

**Comment by IamDeshRaj** [comment]
Yes this is an issue that I'm not able to resolve. It is related to the serverless path(serverless.yml) but once you will deploy it on AWS lambda and map AWS lambda URL it to your domain, this issue vanishes automatically. e.g. have a look into my [domain](https://www.mypleaks.com). You can test the same with your domain for once. Due to the time constraint, I didn't put more effort into it, Sorry for that.

**Comment by quedicesebas** [comment]
Ok! How to map AWS lambda URL to my domain? Thanks

**Comment by IamDeshRaj** [comment]
Follow to the link [custom-domain-in-aws-api-gateway](https://medium.com/@maciejtreder/custom-domain-in-aws-api-gateway-a2b7feaf9c74), Thanks to @maciejtreder

**Comment by quedicesebas** [comment]
Thanks!

**Comment by IamDeshRaj** [comment]
I'm closing the issue. Drop the comment if you need additional help.
